#ifndef FormulaParser_h
#define FormulaParser_h

#include "../HilbertIncludes.h"
#include "../Formula/IFormula.h"
#include "../Formula/Containers/Sets/IFormulaSet.h"
#include "../Formula/Containers/AxiomContainer.h"

/*
*
*	This namespace contains the necessary methods
*	to convert a string of formula or formula set
*	into classes derived from IFormula.
*	The formal representation of a formula is
*	generated by this grammar:
*	
*	FORMULA -> ATOM | (FORMULA) | FORMULA -> FORMULA
*	ATOM -> ({a,...,z}U{A,...,Z}U{0,...,9}U{_})* | ~
*	
*	Where ~ is false and an atom can be a string.
*	A formula set's grammar looks like this (inculding the formula's grammar):
*	
*	FORMULAS -> FORMULA | FORMULAS, FORMULAS | {FORMULAS}
*
*/

namespace FormulaParser
{
	IFormula * ParseFormula(string str);
	IFormula * ParseTemp(string str);
	IFormula * ReadFormula(string::iterator& it, string::iterator& end, bool temp);
	IFormula * ReadSingleFormula(string::iterator& it, string::iterator& end, bool temp);

	IFormulaSet * ParseFormulaSet(string str, FSetType type);
	AxiomContainer * ParseAxioms(string str);

	template<typename T>
	bool ReadFormulaSet(string::iterator& it, string::iterator& end, bool temp, T * formulas);
}

#endif